input_config:
  narration_json_path: "/datasets01/ego4d_track2/v1/annotations/narration.json"
  video_dir_path: "/datasets01/ego4d_track2/v1/full_scale/"
transform_config:
  side_size: 256
  crop_size: 224
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
model_config:
  pretrained_text: true
  pretrained_visual: true
  sample_windows: 2
  window_size: 32
  nlp_feature_size: 1024
  visual_feature_size: 768
batch_size: 2
num_workers: 5
prefetch_factor: 1
num_epochs: 1
accelerator: "gpu"
devices: 1
