input_config:
  feature_path: "/checkpoint/miguelmartin/ego4d_track2_features/full_scale/omnivore_video"
  features_per_second: 1.875
  narration_width_sample_sec: 2
  max_num_feature_vec_video_uids: 40
model_config:
  nlp_feature_size: 768
  visual_feature_size: 1024
  proj_dims: [512, 512]
  final_proj_size: 512
k400_pre_config:
  dataset_dir: "/datasets01/Kinetics400_Frames/videos/"
  set_to_use: "val"
  pre_root_dir: "/checkpoint/miguelmartin/vaclip/k400/"
  viz_feature_dir: "viz"
  metadata_out_path: "meta.pth"
  feature_extract_config_path: "/private/home/miguelmartin/ego4d/ego4d_public/ego4d/features/configs/omnivore_video.yaml"
  num_labels_per_machine: 10
  slurm_log_folder: "slurm_log"
  timeout_min: 240
  constraint: "volta"
  slurm_partition: "pixar"
  slurm_array_parallelism: 40
  gpus_per_node: 1
  cpus_per_task: 10
ego_pre_config:
  narration_json_path: "/datasets01/ego4d_track2/v1/annotations/narration.json"
  st_model_name: "all-mpnet-base-v2"
  accelerator: "cuda"
  pre_root_dir: "/checkpoint/miguelmartin/vaclip"
  metadata_out_path: "narrs_meta.pt"
  narration_out_path: "narrs"
  batch_size: 20
  limit: -1
  slurm_log_folder: "slurm_log"
  timeout_min: 240
  constraint: "volta"
  slurm_partition: "pixar"
  slurm_array_parallelism: 25
  gpus_per_node: 1
  cpus_per_task: 10
  num_narrs_per_machine: 250000
batch_size: 40
num_workers: 10
prefetch_factor: 4
num_epochs: 1
accelerator: "gpu"
devices: 1
tb_log_dir: "/private/home/miguelmartin/ego4d/ego4d_public/runs/"
tb_log_name: "vaclip_adam_nl"
slurm_log_folder: "slurm"
lr: 0.0005
beta1: 0.9
beta2: 0.98
wd: 0.2
eps: 1.0e-6
run_locally: false
preprocess_mode: "k400"
eval_per_iter: 1000
