input_config:
  narration_json_path: "/datasets01/ego4d_track2/v1/annotations/narration.json"
  feature_path: "/checkpoint/miguelmartin/ego4d_track2_features/full_scale/omnivore_video"
  features_per_second: 1.875
  narration_width_sample_sec: 2
model_config:
  nlp_feature_size: 768
  visual_feature_size: 1024
  proj_dims: [1024, 1024]
  final_proj_size: 256
pre_config:
  st_model_name: "all-mpnet-base-v2"
  accelerator: "cuda"
  pre_root_dir: "/checkpoint/miguelmartin/vaclip_test"
  metadata_out_path: "pre.pt"
  narration_out_path: "narrs"
  batch_size: 64
  limit: 1000
batch_size: 30000
num_workers: 10
prefetch_factor: 2
num_epochs: 1000
accelerator: "gpu"
devices: 1
tb_log_dir: "/private/home/miguelmartin/ego4d/ego4d_public/runs/"
tb_log_name: "test_vaclip_30k_bs"
slurm_log_folder: "slurm"
