input_config:
  feature_path: "/checkpoint/miguelmartin/ego4d_track2_features/full_scale/omnivore_video_swinL"
  features_per_second: 1.875
  narration_width_sample_sec: 2
  max_num_feature_vec_video_uids: 30
model_config:
  nlp_feature_size: 768
  visual_feature_size: 1536
  proj_dims: [512, 512]
  final_proj_size: 512
k400_pre_config:
  dataset_dir: "/datasets01/Kinetics400_Frames/videos/"
  set_to_use: "val"
  pre_root_dir: "/checkpoint/miguelmartin/vaclip/k400/"
  viz_feature_dir: "viz"
  metadata_out_path: "meta.pth"
  feature_extract_config_path: "/private/home/miguelmartin/ego4d/ego4d_vaclip/ego4d/features/configs/omnivore_video.yaml"
  num_labels_per_machine: 400
  slurm_log_folder: "slurm_log"
  timeout_min: 60
  constraint: "volta"
  slurm_partition: "pixar"
  slurm_array_parallelism: 50
  gpus_per_node: 1
  cpus_per_task: 10
ego_pre_feature_config:
  hdf5_path: "/checkpoint/miguelmartin/vaclip/features.hdf5"
ego_pre_config:
  narration_json_path: "/datasets01/ego4d_track2/v1/annotations/narration.json"
  st_model_name: "all-mpnet-base-v2"
  accelerator: "cuda"
  pre_root_dir: "/checkpoint/miguelmartin/vaclip"
  metadata_out_path: "narrs_meta.pt"
  narration_out_path: "narrs"
  batch_size: 50
  limit: -1
  slurm_log_folder: "slurm_log"
  timeout_min: 240
  constraint: "volta"
  slurm_partition: "pixar"
  slurm_array_parallelism: 100
  gpus_per_node: 1
  cpus_per_task: 10
  num_narrs_per_machine: 50000
batch_size: 50
num_workers: 10
prefetch_factor: 3
num_epochs: 2
accelerator: "gpu"
devices: 1
tb_log_dir: "/private/home/miguelmartin/ego4d/ego4d_vaclip/runs"
tb_log_name: "vaclip_adam_nl_bs30_lr1e-3_wd_0.1_test"
slurm_log_folder: "slurm"
lr: 0.001
beta1: 0.9
beta2: 0.98
wd: 0.1
eps: 1.0e-6
run_locally: false
preprocess_mode: "ego_features"
eval_per_iter: 1000
