input_config:
  feature_path: "/checkpoint/miguelmartin/ego4d_track2_features/full_scale/omnivore_video_swinL"
  feature_extract_config_path: "/private/home/miguelmartin/ego4d/ego4d_vaclip/ego4d/features/configs/omnivore_video.yaml"
  features_per_second: 1.875
  narration_width_sample_sec: 2
  max_num_feature_vec_video_uids: 30
model_config:
  nlp_feature_size: 768
  visual_feature_size: 1536
  proj_dims: [512, 512]
  final_proj_size: 512
pre_config:
  ego_charade:
    out_path: "/checkpoint/miguelmartin/vaclip/charades.hdf5"
    out_label_path: "/checkpoint/miguelmartin/vaclip/labels.pt"
    timeout_min: 240
    constraint: "volta"
    slurm_log_folder: "slurm_log"
    slurm_partition: "learnaccel"
    slurm_array_parallelism: 20
    gpus_per_node: 1
    cpus_per_task: 10
    num_vids_per_machine: 80
  k400:
    dataset_dir: "/datasets01/Kinetics400_Frames/videos/"
    set_to_use: "val"
    pre_root_dir: "/checkpoint/miguelmartin/vaclip/k400/"
    viz_feature_dir: "viz"
    metadata_out_path: "meta.pth"
    num_labels_per_machine: 400
    slurm_log_folder: "slurm_log"
    timeout_min: 60
    constraint: "volta"
    slurm_partition: "pixar"
    slurm_array_parallelism: 50
    gpus_per_node: 1
    cpus_per_task: 10
  ego4d_features:
    hdf5_path: "/checkpoint/miguelmartin/vaclip/features.hdf5"
  ego4d_narr:
    narration_json_path: "/datasets01/ego4d_track2/v1/annotations/narration.json"
    st_model_name: "all-mpnet-base-v2"
    accelerator: "cuda"
    pre_root_dir: "/checkpoint/miguelmartin/vaclip"
    metadata_out_path: "narrs_meta_no_tag.pt"
    narration_out_path: "narrs_w_no_tag"
    batch_size: 50
    limit: -1
    slurm_log_folder: "slurm_log"
    timeout_min: 240
    constraint: "volta"
    slurm_partition: "pixar"
    slurm_array_parallelism: 100
    gpus_per_node: 1
    cpus_per_task: 10
    num_narrs_per_machine: 50000
batch_size: 128
num_workers: 10
prefetch_factor: 4
num_epochs: 200
accelerator: "gpu"
devices: 1
tb_log_dir: "/private/home/miguelmartin/ego4d/ego4d_vaclip/runs"
tb_log_name: "clip_loss"
slurm_log_folder: "slurm"
lr: 0.001
beta1: 0.9
beta2: 0.98
wd: 0.1
eps: 1.0e-6
run_locally: false
preprocess_mode: "ego_charade"
eval_per_iter: 2000
eval_init: false
use_soft_loss: false
use_bce: false
norm_logits: false
soft_loss_threshold: 0.8
use_logit_scale: true
